### ISSUE TITLE
Add media image

### ISSUE THREAD

**Issue by lindsaymarkward** [calmor15014/HA-Component-mythtv-frontend#17]
Implement media_image_url with image from API call to Dvr/GetRecordedList (using title from Frontend/GetStatus
See also:
https://forum.mythtv.org/viewtopic.php?f=33&t=2128&p=10538#p10538

**Comment by calmor15014** [comment]
It looks like ```zoneminder``` is its own component class. I don't know if we want to go that far, having a MythTV component class and frontend and backend components in various other component classes. So, maybe just backend config in the YAML is okay, considering most probably run a combined system.

**Comment by lindsaymarkward** [comment]
Right! I hadn't remembered about separate backend/frontend systems or multiple frontends... I've only ever had one combined machine.
For now, how about we just add `host_backend` to the config (assume one BE and one FE which may be different). Then we could update to handle multiple entries (list) in the config - making one object for each. I think just specifying the BE & FE & name for each would be simple (even if the BE are all the same).

**Comment by calmor15014** [comment]
Agreed for the ```host_backend``` addition which is optional and assumes joint FE/BE (likely most common).  Even with several frontends, it is still simple enough to manage - especially since the ports are almost always default anyway.

**Comment by lindsaymarkward** [comment]
I've almost finished adding the `host_backend` config. Just need to clean up something before another PR...

**Comment by calmor15014** [comment]
I've been busy at work but may have a little time this weekend to work on some things as well.

**Comment by lindsaymarkward** [comment]
I got a response from the MythTV experts (Bill) at https://forum.mythtv.org/viewtopic.php?f=33&t=2128&p=10578#p10578 and I've updated the media image fetching to be much more efficient 👍

**Comment by calmor15014** [comment]
Works perfectly with my split backend / frontend system, considering this closed.
