### ISSUE TITLE
SendAction workaround for MythTV 0.28+

### ISSUE THREAD

**Issue by calmor15014** [calmor15014/HA-Component-mythtv-frontend#2]
As SendAction doesn't work in 0.28+ based on Trac bug reports and testing, similar functionality could be resolved by using SendKey. However, custom user keymaps could complicate that, requiring configuration capabilities to override default key sequences. Also, keys are not consistent between screens, which could cause a problem with control.

**Comment by lindsaymarkward** [comment]
Can you post a link to a Trac bug report? A quick Google search didn't reveal anything for me.

**Comment by calmor15014** [comment]
I'm actually just going to close this, as my system is also 0.28 and responds normally to SendAction.  It's apparently just my VM system that I'd been testing on that is the problem.  If future users have issues with 0.29 (when it's out of beta), we can deal with them at that time.
