### ISSUE TITLE
Implement power off function

### ISSUE THREAD

**Issue by calmor15014** [calmor15014/HA-Component-mythtv-frontend#3]
Frontend does not have a default method of triggering power off event. Consider adding a configurable system event triggered by SendAction or SendKey to shut down the frontend.

**Comment by gmschade** [comment]
see pull request [#36](https://github.com/calmor15014/HA-Component-mythtv-frontend/pull/36l)

**Comment by calmor15014** [comment]
Tested and works well.  Thanks!
