### ISSUE TITLE
Use new location for MythTV Services API

### ISSUE THREAD

**Issue by lindsaymarkward** [calmor15014/HA-Component-mythtv-frontend#31]
Services API has moved from:
https://github.com/billmeek/MythTVServicesAPI
to: https://github.com/MythTV/mythtv/tree/master/mythtv/bindings/python/MythTV/services_api

**Comment by lindsaymarkward** [comment]
Bill says "The github version won't go away soon, just won't get updates (since v30.0 just
got released.)"
https://forum.mythtv.org/viewtopic.php?f=33&t=3039&p=14725#p14725
So we don't need to do this imminently. Wait until there's an installable version.

**Comment by calmor15014** [comment]
You guys have been busy! I unfortunately just got another job dumped on me at work (up to three now, go me!) so I'm hoping to get at all of the comments and changes this weekend if I can.  I'm good with passing commit privileges to you and Bill as well if you want to keep moving on - I wouldn't be offended.  My prod environments are still MythTV 0.28 and Home Assistant 0.63.1,

**Comment by calmor15014** [comment]
Closing to implement #41 instead.
