### ISSUE TITLE
Fix invalid host vs. no-communication error logging and status updating

### ISSUE THREAD

**Issue by calmor15014** [calmor15014/HA-Component-mythtv-frontend#4]
Passing an invalid host (i.e. 333.333.333.333) indicates frontend is off in the frontend instead of warning the user of invalid configuration. All errors communicating with the host indicate that the frontend is off. Consider using ping functionality to determine if the machine is off/untraceable vs. status unknown.

**Comment by lindsaymarkward** [comment]
I'm happy to look into this next.

**Comment by calmor15014** [comment]
@lindsaymarkward I did play around with this code a little today and was able to implement a ping function that checked to see if the host responded to a ping.  If you're still working on this one, I can wait to make any changes until you do a PR.

**Comment by lindsaymarkward** [comment]
No, go ahead. I've only looked, not written anything.

**Comment by calmor15014** [comment]
Okay. I was actually trying to address the second part of this issue of handling when the frontend is actually off vs. not running, but it doesn't fully validate a host. Not even sure if that can be done. 

Have to make a small tweak or two yet, but my log was filling up with API timeouts when the device was off.

**Comment by calmor15014** [comment]
Latest update to master adds ping to differentiate between hosts which are truly off/inaccessible and hosts which are up but not responding to the API.  Off will allow WOL packet to be sent if the mac address is configured.  MythTV versions prior to 0.27 should also show up as unknowns.  I don't know if there's a way to actually test if the host is valid (and if we should get into that, anyway).  If so, this can be reopened.
