### ISSUE TITLE
Consider using GetFrontends backend service

### ISSUE THREAD

**Issue by calmor15014** [calmor15014/HA-Component-mythtv-frontend#43]
Pinging to check for online frontends is inherently slow; if the host is online it should respond immediately, but offline will wait until timeout.  Consider using `Myth/GetFrontends` service, available since at least 0.30, to confirm if frontends are listed as connected to the backend server.

Could also be used in autodiscovery once the backend service is loaded.  (Not sure how to make persistent in HA, as I have several frontends which have not been online in a while and are absent from that list, however every hostname ever connected does show up in `Myth/GetHosts` so that's one option)

**Comment by rajlaud** [comment]
I recently implemented something similar in the `squeezebox` integration- players come and go, but the server stays the same. I polled the server to autodiscover (and rediscover) players. Happy to attempt a PR unless this is already in progress.

**Comment by calmor15014** [comment]
Closed via #47
